# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "love2d-feedstock"
version = "3.48.1"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/love2d-feedstock"
authors = ["@conda-forge/love2d"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build love2d-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_variantlatest"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_variantlatest.yaml"
description = "Build love2d-feedstock with variant linux_64_variantlatest directly (without setup scripts)"
[tasks."inspect-linux_64_variantlatest"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_variantlatest.yaml"
description = "List contents of love2d-feedstock packages built for variant linux_64_variantlatest"
[tasks."build-linux_64_variantlua51"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_variantlua51.yaml"
description = "Build love2d-feedstock with variant linux_64_variantlua51 directly (without setup scripts)"
[tasks."inspect-linux_64_variantlua51"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_variantlua51.yaml"
description = "List contents of love2d-feedstock packages built for variant linux_64_variantlua51"
[tasks."build-linux_64_variantluajit"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_variantluajit.yaml"
description = "Build love2d-feedstock with variant linux_64_variantluajit directly (without setup scripts)"
[tasks."inspect-linux_64_variantluajit"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_variantluajit.yaml"
description = "List contents of love2d-feedstock packages built for variant linux_64_variantluajit"
[tasks."build-osx_64_variantlatest"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_variantlatest.yaml"
description = "Build love2d-feedstock with variant osx_64_variantlatest directly (without setup scripts)"
[tasks."inspect-osx_64_variantlatest"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_variantlatest.yaml"
description = "List contents of love2d-feedstock packages built for variant osx_64_variantlatest"
[tasks."build-osx_64_variantlua51"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_variantlua51.yaml"
description = "Build love2d-feedstock with variant osx_64_variantlua51 directly (without setup scripts)"
[tasks."inspect-osx_64_variantlua51"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_variantlua51.yaml"
description = "List contents of love2d-feedstock packages built for variant osx_64_variantlua51"
[tasks."build-osx_64_variantluajit"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_variantluajit.yaml"
description = "Build love2d-feedstock with variant osx_64_variantluajit directly (without setup scripts)"
[tasks."inspect-osx_64_variantluajit"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_variantluajit.yaml"
description = "List contents of love2d-feedstock packages built for variant osx_64_variantluajit"
[tasks."build-osx_arm64_variantlatest"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_variantlatest.yaml"
description = "Build love2d-feedstock with variant osx_arm64_variantlatest directly (without setup scripts)"
[tasks."inspect-osx_arm64_variantlatest"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_variantlatest.yaml"
description = "List contents of love2d-feedstock packages built for variant osx_arm64_variantlatest"
[tasks."build-osx_arm64_variantlua51"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_variantlua51.yaml"
description = "Build love2d-feedstock with variant osx_arm64_variantlua51 directly (without setup scripts)"
[tasks."inspect-osx_arm64_variantlua51"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_variantlua51.yaml"
description = "List contents of love2d-feedstock packages built for variant osx_arm64_variantlua51"
[tasks."build-osx_arm64_variantluajit"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_variantluajit.yaml"
description = "Build love2d-feedstock with variant osx_arm64_variantluajit directly (without setup scripts)"
[tasks."inspect-osx_arm64_variantluajit"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_variantluajit.yaml"
description = "List contents of love2d-feedstock packages built for variant osx_arm64_variantluajit"
[tasks."build-win_64_variantlatest"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_variantlatest.yaml"
description = "Build love2d-feedstock with variant win_64_variantlatest directly (without setup scripts)"
[tasks."inspect-win_64_variantlatest"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_variantlatest.yaml"
description = "List contents of love2d-feedstock packages built for variant win_64_variantlatest"
[tasks."build-win_64_variantlua51"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_variantlua51.yaml"
description = "Build love2d-feedstock with variant win_64_variantlua51 directly (without setup scripts)"
[tasks."inspect-win_64_variantlua51"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_variantlua51.yaml"
description = "List contents of love2d-feedstock packages built for variant win_64_variantlua51"
[tasks."build-win_64_variantluajit"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_variantluajit.yaml"
description = "Build love2d-feedstock with variant win_64_variantluajit directly (without setup scripts)"
[tasks."inspect-win_64_variantluajit"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_variantluajit.yaml"
description = "List contents of love2d-feedstock packages built for variant win_64_variantluajit"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
